name: Build ImmortalWrt Multi-Arch

on:
  workflow_dispatch:
    inputs:
      version:
        description: "ImmortalWrt 版本"
        required: true
        default: '24.10.6'
      target_arch:
        description: "选择目标架构"
        required: true
        type: choice
        options:
          - x86-64
          - rockchip-armv8
          - mediatek-filogic
          - broadcom-bcm27xx
      rom_size:
        description: "固件大小(MB)"
        required: true
        default: '512'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build firmware
        run: |
          # 拆分选择的架构为 Target 和 Subtarget
          # 例如 x86-64 -> TARGET=x86, SUBTARGET=64
          IFS='-' read -r TARGET SUBTARGET <<< "${{ github.event.inputs.target_arch }}"
          
          docker run --rm -i \
            -v "${{ github.workspace }}:/home/build/custom" \
            -e TARGET=$TARGET \
            -e SUBTARGET=$SUBTARGET \
            -e PROFILE=$ROM_SIZE \
            -e VERSION=${{ github.event.inputs.version }} \
            immortalwrt/imagebuilder:${TARGET}-${SUBTARGET}-openwrt-${{ github.event.inputs.version }} \
            /bin/bash /home/build/custom/scripts/build.sh