name: "Step 1: 选择版本"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "选择 ImmortalWrt 版本"
        required: true
        type: choice
        options:
          - 24.10.6
          - 24.10.5

permissions:
  contents: write
  actions: write

jobs:
  get-archs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: 获取架构列表
        run: |
          VERSION="${{ github.event.inputs.version }}"
          TOKEN=$(curl -s "https://auth.docker.io/token?service=registry.docker.io&scope=repository:immortalwrt/imagebuilder:pull" | jq -r '.token')
          
          curl -sH "Authorization: Bearer $TOKEN" \
            "https://registry-1.docker.io/v2/immortalwrt/imagebuilder/tags/list?n=1000" | \
            jq -r '.tags[]' | grep "openwrt-${VERSION}" | sed "s/-openwrt-${VERSION}//" | sort -u | head -20